export interface BrandHubProfile {
  title: string
  h1: string
  description: string
  overview: string
  applications: string[]
  howToChoose: string[]
  featuredModels: string[]
  commonSearches: string[]
  links: { label: string; href: string }[]
  cta: {
    title: string
    body: string
    primaryLabel: string
    primaryHref: string
    secondaryLabel: string
    secondaryHref: string
  }
}

const CONTACT_URL = 'https://www.haifengmachinery.com/contact-us/'
const DIESEL_REGULATED_URL = 'https://www.haifengmachinery.com/diesel-power-package-regulated/'
const DIESEL_NON_REGULATED_URL = 'https://www.haifengmachinery.com/product-offerings/'
const GAS_PACKAGE_URL = 'https://www.haifengmachinery.com/gas-power-package-50hz-60hz/'
const TOWABLE_PACKAGE_URL = 'https://www.haifengmachinery.com/towable-power-package/'
const CUSTOM_EPC_URL = 'https://www.haifengmachinery.com/custom-epc-power-solutions/'

export const BRAND_HUB_PROFILES: Record<string, BrandHubProfile> = {
  'baudouin': {
    title: 'Baudouin Generators & Diesel Engine Specs',
    h1: 'Baudouin Generator Engines',
    description: 'Browse Baudouin generator engine specs for diesel generator sets, including 4M, 6M, 8M, 12M and 16M model families, kWe ratings, emissions and datasheets.',
    overview: 'Baudouin is a high-interest generator brand in this database, especially for diesel generator buyers comparing Moteurs Baudouin engine ratings, datasheets and emissions variants. The catalog covers compact 4M-series models through 12M33 and 16M33 high-power diesel generator-drive packages.',
    applications: [
      'High-power standby generator sets for industrial facilities and data centers',
      'Prime-power diesel packages for mining, oil and gas, rental and remote sites',
      'EPA Tier 2 regulated diesel packages where emissions documentation matters',
      'Unregulated-market diesel generator packages for export projects',
      'Gas and biogas generator-set projects where Baudouin gaseous-fuel models fit the site fuel supply',
    ],
    howToChoose: [
      'Start by selecting the required kWe band, then compare the closest Baudouin standby and prime ratings instead of comparing model names alone.',
      'Check whether the project needs an EPA Tier 2, China-market, gas/biogas or unregulated-market engine variant.',
      'Use the datasheet link on each model page to confirm radiator power, fuel consumption, dimensions and alternator matching before quoting a full genset.',
      'For large 12M55 and 16M55 engines, confirm voltage, alternator frame, enclosure access, cooling airflow and site altitude early.',
    ],
    featuredModels: [
      'baudouin-16m33g2250-5',
      'baudouin-16m33g2000-5',
      'baudouin-16m33g1900-5',
      'baudouin-16m33g1700-5',
      'baudouin-12m33g1650-5',
      'baudouin-12m33g1500-5',
      'baudouin-12m26g1100-5',
      'baudouin-6m21g550-5',
    ],
    commonSearches: [
      'baudouin generator',
      'baudouin generators',
      'baudouin generator review',
      'baudouin diesel generator engine',
      'moteurs baudouin generator',
      'baudouin engine datasheet',
    ],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'EPA standby diesel packages', href: DIESEL_REGULATED_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Baudouin high-power engines', href: '/engines/power/1500-plus-kwe' },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: 'EPA Tier 2 engines', href: '/engines/emissions/epa-tier-2' },
      { label: 'Generator engine selection guide', href: '/guides/how-to-choose-a-generator-engine' },
    ],
    cta: {
      title: 'Need a Baudouin generator package?',
      body: 'Haifeng Machinery can help compare Baudouin engine ratings, match the alternator, select regulated or non-regulated diesel packages, and quote a complete generator set for your site conditions.',
      primaryLabel: 'Request Baudouin package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Diesel generator packages',
      secondaryHref: DIESEL_REGULATED_URL,
    },
  },
  'jenbacher': {
    title: 'Jenbacher Generators & Gas Engine Specs',
    h1: 'Jenbacher Gas Generator Engines',
    description: 'Browse Jenbacher gas generator engine specs for CHP, prime power and industrial generators, from the J208 through the 10.6 MW J920 FleXtra, with 50 Hz and 60 Hz ratings and datasheets.',
    overview: 'Jenbacher is a gas-engine generator brand in this database, with current Type 2, 3, 4, 6 and 9 natural-gas models for CHP, prime power, industrial power and utility-scale projects. Use this hub to compare J-series 50 Hz and 60 Hz output, displacement, configuration and official datasheet coverage before sizing the full generator package.',
    applications: [
      'Natural-gas CHP and cogeneration plants',
      'Industrial prime-power generator systems',
      'Biogas and gas-to-power projects where site fuel quality can be verified',
      'Large commercial backup systems with gas supply available',
    ],
    howToChoose: [
      'Start with fuel quality and gas supply, then compare the J-series electrical output band.',
      'Confirm heat-recovery, CHP and emissions requirements before comparing gas engines to diesel alternatives.',
      'Check alternator voltage, grid interconnection and controls with the engine rating.',
    ],
    featuredModels: ['jenbacher-j920-flextra', 'jenbacher-j624', 'jenbacher-j620', 'jenbacher-j616', 'jenbacher-j420'],
    commonSearches: ['jenbacher generators', 'jenbacher gas engines', 'jenbacher industrial generators', 'jenbacher generator specs'],
    links: [
      { label: 'CNG and LPG gas generator systems', href: GAS_PACKAGE_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: '1,500+ kWe engines', href: '/engines/power/1500-plus-kwe' },
      { label: 'Gas vs diesel TCO guide', href: '/guides/diesel-vs-natural-gas-total-cost-of-ownership' },
    ],
    cta: {
      title: 'Need help comparing Jenbacher gas packages?',
      body: 'Haifeng Machinery can help review gas engine output, alternator matching, controls and fuel-system requirements for gas generator projects.',
      primaryLabel: 'Request gas package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Gas generator packages',
      secondaryHref: GAS_PACKAGE_URL,
    },
  },
  'hino': {
    title: 'Hino Generator Engine Specs',
    h1: 'Hino Generator Engines',
    description: 'Browse Hino generator engine specs for diesel gensets, including P11C, J08E, W06E, J05E and W04D model ratings for compact and mid-range packages.',
    overview: 'Hino generator engines in this database cover compact and mid-range diesel generator sets, with inline engines such as P11C, J08E, W06E, J05E and W04D. Use this hub for genset Hino model lookup, power range checks and package selection context.',
    applications: [
      'Commercial standby generator sets',
      'Telecom, small industrial and facility backup power',
      'Compact diesel generator packages where serviceability and size matter',
    ],
    howToChoose: [
      'Match the Hino model to the required kWe band first, then verify whether a datasheet is available.',
      'Confirm the target market emissions requirement before using an unregulated engine in a quotation.',
      'Check alternator size and enclosure cooling for compact diesel packages.',
    ],
    featuredModels: ['hino-p11c', 'hino-j08e', 'hino-w06e', 'hino-j05e', 'hino-w04d'],
    commonSearches: ['genset hino', 'hino generator', 'hino generator engine', 'hino diesel generator'],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'EPA standby diesel packages', href: DIESEL_REGULATED_URL },
      { label: 'Under 100 kWe engines', href: '/engines/power/under-100-kwe' },
      { label: '100-500 kWe engines', href: '/engines/power/100-500-kwe' },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
    ],
    cta: {
      title: 'Need a compact Hino diesel generator package?',
      body: 'Haifeng Machinery can help compare Hino model output with alternator, controller, enclosure and voltage requirements for compact diesel gensets.',
      primaryLabel: 'Request Hino package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Diesel generator packages',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
  'jcb': {
    title: 'JCB Generator Engine Specs',
    h1: 'JCB Generator Engines',
    description: 'Browse JCB generator engine specs for diesel gensets, including 448 engines with Stage V, EPA Tier 4 Final and Tier 3 variants for regulated generator packages.',
    overview: 'JCB generator engines in this database focus on 4.8 L inline-4 diesel models for compact regulated generator sets. The hub is useful for buyers comparing Stage V, EPA Tier 4 Final and EPA Tier 3 JCB 448 variants by output, emissions level and datasheet coverage.',
    applications: [
      'Regulated-market compact diesel generator sets',
      'Rental, construction and industrial standby packages',
      'Projects where Stage V or EPA Tier 4 Final documentation is required',
    ],
    howToChoose: [
      'Choose the emissions family first: Stage V, EPA Tier 4 Final or EPA Tier 3.',
      'Compare the 448 model output band against the standby or prime kWe requirement.',
      'Use the datasheet to confirm aftertreatment, cooling and installation constraints before packaging.',
    ],
    featuredModels: ['jcb-448-sv-129', 'jcb-448-ta4f-110', 'jcb-448-ta3-100', 'jcb-448-ta3-75', 'jcb-448-ta4f-75'],
    commonSearches: ['jcb generators', 'jcb generator', 'jcb diesel generators', 'jcb generator engine'],
    links: [
      { label: 'Rental and towable power', href: TOWABLE_PACKAGE_URL },
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'EPA Tier 4 Final engines', href: '/engines/emissions/epa-tier-4-final' },
      { label: 'Euro Stage V engines', href: '/engines/emissions/euro-stage-v' },
      { label: 'Under 100 kWe engines', href: '/engines/power/under-100-kwe' },
    ],
    cta: {
      title: 'Need a JCB regulated diesel generator package?',
      body: 'Haifeng Machinery can help confirm JCB engine output, emissions compliance, alternator matching and enclosure requirements for regulated diesel gensets.',
      primaryLabel: 'Request JCB package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Regulated diesel packages',
      secondaryHref: DIESEL_REGULATED_URL,
    },
  },
  'liebherr': {
    title: 'Liebherr Generators & Engine Specs',
    h1: 'Liebherr Generator Engines',
    description: 'Browse Liebherr generator engine specs for diesel and gas generator applications, including model ratings, fuel type, emissions context and datasheet references.',
    overview: 'Liebherr generator engines in this database are relevant for buyers comparing heavy-duty diesel and gas engine platforms for industrial power, project power and engineered generator packages. Use this hub to compare output, displacement, emissions tags, fuel type and datasheet coverage before selecting the full generator-set package.',
    applications: [
      'Industrial standby and prime-power generator packages',
      'Containerized generator projects for remote or harsh environments',
      'Gas generator projects where the fuel supply and operating profile are stable',
      'Mining, construction, oil and gas, and heavy industrial power systems',
      'Custom EPC projects requiring coordinated engine, alternator, enclosure and controls review',
    ],
    howToChoose: [
      'Start with the site duty, because a Liebherr engine used for routine prime power has different package requirements from a standby unit.',
      'Compare diesel and gas options against fuel availability, operating hours, ambient temperature and service access.',
      'Confirm alternator voltage, cooling airflow, enclosure or container layout, and emissions documentation before treating the engine rating as final.',
    ],
    featuredModels: ['liebherr-d976', 'liebherr-d9508', 'liebherr-d9512', 'liebherr-g9512'],
    commonSearches: ['liebherr generator', 'liebherr generators', 'liebherr engine', 'liebherr gas engines', 'liebherr generator engine'],
    links: [
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'CNG and LPG gas generator systems', href: GAS_PACKAGE_URL },
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: 'Generator paralleling guide', href: '/guides/generator-paralleling-explained' },
    ],
    cta: {
      title: 'Need a Liebherr generator package review?',
      body: 'Haifeng Machinery can help compare Liebherr diesel or gas engine options with alternator, cooling, enclosure, controls and documentation requirements for engineered generator projects.',
      primaryLabel: 'Request Liebherr package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Custom EPC power solutions',
      secondaryHref: CUSTOM_EPC_URL,
    },
  },
  'mtu': {
    title: 'MTU Generators & Engine Specs',
    h1: 'MTU Generator Engines',
    description: 'Browse MTU generator engine specs for diesel and gas generator sets, including Series 2000 and Series 4000 model ratings, emissions context and datasheet references.',
    overview: 'MTU generator engines in this database cover high-value diesel and gas generator applications, including Series 2000 and Series 4000 model families used in standby, prime, data center, industrial and project-power packages. Use this hub to compare model output, fuel type, emissions context and datasheet coverage before selecting the full generator system.',
    applications: [
      'Mission-critical standby power for data centers and commercial facilities',
      'High-power diesel generator packages for industrial and export projects',
      'Gas generator systems where the project favors gaseous fuel and long runtime',
      'Parallel generator systems and custom EPC packages',
      'Projects where service access, documentation and alternator matching must be reviewed early',
    ],
    howToChoose: [
      'Start by separating Series 2000 and Series 4000 options, then compare the kWe band and fuel type against the project duty.',
      'Check whether the project needs diesel standby, gas operation, EPA-oriented documentation or a non-regulated export-market package.',
      'Confirm voltage, frequency, alternator frame, cooling package, controls and enclosure space before quoting a complete MTU-based generator set.',
    ],
    featuredModels: ['mtu-20v4000-g83', 'mtu-20v4000-g63', 'mtu-16v4000-g83', 'mtu-12v4000-g84f', 'mtu-18v2000-g85'],
    commonSearches: ['mtu generators', 'mtu generator', 'mtu engine models', 'mtu gas engines', 'mtu 20v4000'],
    links: [
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'EPA standby diesel packages', href: DIESEL_REGULATED_URL },
      { label: 'CNG and LPG gas generator systems', href: GAS_PACKAGE_URL },
      { label: '1,500+ kWe engines', href: '/engines/power/1500-plus-kwe' },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
    ],
    cta: {
      title: 'Need an MTU generator package review?',
      body: 'Haifeng Machinery can help compare MTU engine ratings with alternator, controller, enclosure, voltage, fuel, emissions and project documentation requirements.',
      primaryLabel: 'Request MTU package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Custom EPC power solutions',
      secondaryHref: CUSTOM_EPC_URL,
    },
  },
  'scania': {
    title: 'Scania Generator Engine Specs',
    h1: 'Scania Generator Engines',
    description: 'Browse Scania generator engine specs for industrial diesel generator sets, including model ratings, emissions context, datasheets and generator package selection notes.',
    overview: 'Scania generator engines in this database are relevant for industrial diesel generator packages, export projects and standby or prime-power applications where buyers need dependable model-level specification data. Use this hub to compare output, displacement, emissions tags and datasheet coverage before selecting the complete generator-set package.',
    applications: [
      'Industrial standby and prime diesel generator packages',
      'Export-market generator projects where serviceability and documentation matter',
      'Commercial facilities, construction sites, remote facilities and municipal backup power',
      'Project power packages that need coordinated engine, alternator, enclosure and controls review',
    ],
    howToChoose: [
      'Start with the required kWe/kVA band and frequency, then compare Scania ratings against standby or prime duty.',
      'Confirm the destination-market emissions requirement before using the engine model in a quotation.',
      'Review alternator voltage, cooling airflow, enclosure layout and site access before treating the engine rating as final.',
    ],
    featuredModels: ['scania-dc13-507a-500', 'scania-dc13-507a-600', 'scania-dc16-093a-02-54', 'scania-dc16-078a-02-44'],
    commonSearches: ['scania generator', 'scania generators', 'scania generator engine', 'scania diesel generator'],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: '500-1,500 kWe engines', href: '/engines/power/500-1500-kwe' },
      { label: 'Generator engine selection guide', href: '/guides/how-to-choose-a-generator-engine' },
    ],
    cta: {
      title: 'Need a Scania generator package review?',
      body: 'Haifeng Machinery can help compare Scania engine options with alternator, cooling, enclosure, controller, emissions and documentation requirements for complete generator-set projects.',
      primaryLabel: 'Request Scania package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Custom EPC power solutions',
      secondaryHref: CUSTOM_EPC_URL,
    },
  },
  'fpt': {
    title: 'FPT Generator Engine Specs',
    h1: 'FPT Generator Engines',
    description: 'Browse FPT generator engine specs for compact and mid-range diesel gensets, including model ratings, fuel, emissions, datasheet coverage and package context.',
    overview: 'FPT generator engines in this database are useful for buyers comparing compact and mid-range diesel generator packages. Use this hub to review model ratings, displacement, fuel, emissions context and datasheet references before moving into generator package selection.',
    applications: [
      'Commercial standby diesel generator packages',
      'Agricultural, telecom, light industrial and facility backup power',
      'Compact and mid-range gensets where engine size, service access and enclosure fit matter',
    ],
    howToChoose: [
      'Select the required kWe/kVA band first, then compare FPT model ratings against the actual standby or prime load.',
      'Check voltage, frequency, alternator frame and enclosure cooling before finalizing the package.',
      'Confirm whether the project needs regulated-market documentation or an export-market configuration.',
    ],
    featuredModels: ['fpt-f34tevp01-00', 'fpt-nef45sm1x', 'fpt-nef67-te3pv', 'fpt-c87-te3f', 'fpt-c13-te2f'],
    commonSearches: ['fpt generator', 'fpt generators', 'fpt generator engine', 'fpt diesel generator'],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: '100-500 kWe engines', href: '/engines/power/100-500-kwe' },
      { label: 'Generator sizing guide', href: '/guides/how-to-size-a-generator' },
      { label: 'Alternator matching guide', href: '/guides/alternator-voltage-and-frequency' },
    ],
    cta: {
      title: 'Need an FPT diesel generator package?',
      body: 'Haifeng Machinery can help compare FPT engine ratings with alternator, controller, enclosure, voltage and project documentation requirements for compact and mid-range generator packages.',
      primaryLabel: 'Request FPT package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Product offerings',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
  'guascor': {
    title: 'Guascor Gas Generator Engine Specs',
    h1: 'Guascor Gas Generator Engines',
    description: 'Browse Guascor gas generator engine specs for industrial power and gas-to-power projects, including model ratings, fuel context, datasheets and package notes.',
    overview: 'Guascor generator engines in this database are most relevant for buyers comparing gas-engine generator projects. Use this hub to review ratings, displacement, fuel and datasheet references before evaluating gas train, controls, cooling, emissions and complete generator package requirements.',
    applications: [
      'Industrial gas generator systems',
      'Gas-to-power and continuous-duty projects with stable gaseous fuel supply',
      'Remote or project power applications where fuel quality and service planning must be checked early',
      'Custom EPC gas generator projects requiring coordinated engine, alternator, cooling and controls review',
    ],
    howToChoose: [
      'Start with fuel type and gas quality, then compare Guascor model output against the site load profile.',
      'Confirm prime or continuous-duty expectations before using a gas-engine rating in a quote.',
      'Review gas train, cooling, controls, emissions and grid interconnection before final package selection.',
    ],
    featuredModels: ['guascor-g-56sl', 'guascor-g-48fl', 'guascor-g-42hm', 'guascor-g-36fl'],
    commonSearches: ['guascor engines', 'guascor generator', 'guascor gas engine', 'guascor gas generator'],
    links: [
      { label: 'CNG and LPG gas generator systems', href: GAS_PACKAGE_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: 'Gas vs diesel TCO guide', href: '/guides/diesel-vs-natural-gas-total-cost-of-ownership' },
      { label: 'Generator paralleling guide', href: '/guides/generator-paralleling-explained' },
    ],
    cta: {
      title: 'Need a Guascor gas generator package review?',
      body: 'Haifeng Machinery can help compare Guascor gas engine options with alternator, gas train, cooling, controller, fuel and documentation requirements for complete gas generator projects.',
      primaryLabel: 'Request Guascor package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Gas generator packages',
      secondaryHref: GAS_PACKAGE_URL,
    },
  },
  'greaves': {
    title: 'Greaves Generator Engine Specs',
    h1: 'Greaves Generator Engines',
    description: 'Browse Greaves generator engine specs for diesel genset research, including model ratings, fuel, emissions context, datasheet links and package selection notes.',
    overview: 'Greaves generator engines in this database support diesel genset research for buyers comparing model identity, output, fuel, emissions context and datasheet coverage. Use this hub as a reference step before selecting the complete generator package.',
    applications: [
      'Commercial and light industrial diesel generator sets',
      'Export-market generator package research',
      'Replacement, sourcing and specification checks for Greaves-powered gensets',
    ],
    howToChoose: [
      'Confirm the exact Greaves model first, because buyers may search by engine, machine or genset naming.',
      'Compare the model rating against standby or prime load before selecting the generator package.',
      'Check voltage, frequency, enclosure, alternator frame and destination-market documentation early.',
    ],
    featuredModels: ['greaves-gpwii-pii-250', 'greaves-gpwii-pii-200', 'greaves-gpwii-pii-62-5', 'greaves-gpwii-pii-25e'],
    commonSearches: ['greaves machine', 'greaves generator', 'greaves genset', 'greaves generator engine'],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: '100-500 kWe engines', href: '/engines/power/100-500-kwe' },
      { label: 'Generator engine selection guide', href: '/guides/how-to-choose-a-generator-engine' },
      { label: 'Generator sizing guide', href: '/guides/how-to-size-a-generator' },
    ],
    cta: {
      title: 'Need a Greaves diesel generator package review?',
      body: 'Haifeng Machinery can help compare Greaves engine options with alternator, controller, enclosure, voltage and export documentation requirements for complete diesel generator packages.',
      primaryLabel: 'Request Greaves package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Product offerings',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
  'weichai': {
    title: 'Weichai Generator Engine Specs',
    h1: 'Weichai Generator Engines',
    description: 'Browse Weichai generator engine specs for diesel and gas gensets, including WP, 6M, 8M, 12M, 16M and 20M model ratings, emissions and datasheets.',
    overview: 'Weichai generator engines in this database cover a broad set of diesel and gas generator-drive models, from compact WP-series engines to large 12M, 16M and 20M industrial power platforms. Use this hub to compare kWe/kVA ratings, 50 Hz and 60 Hz availability, China Stage III, unregulated and gas-engine variants before selecting a complete generator package.',
    applications: [
      'Export-market diesel generator sets where Weichai serviceability and cost structure are important',
      'Industrial standby and prime-power packages from compact WP engines through large M-series platforms',
      'China Stage III and unregulated generator projects where documentation must match the destination market',
      'Gas generator packages using Weichai NG variants where fuel supply and duty cycle are confirmed',
      'Custom EPC projects that need engine, alternator, enclosure, controls and voltage reviewed together',
    ],
    howToChoose: [
      'Start with the project power band, then separate compact WP engines from larger 6M, 8M, 12M, 16M and 20M families.',
      'Confirm whether the job needs diesel, natural gas, China Stage III or unregulated-market documentation before quoting.',
      'Compare standby and prime ratings against actual load profile, site altitude, ambient temperature and runtime expectations.',
      'Use the Weichai datasheet or catalog reference to confirm fuel consumption, cooling margin, alternator matching and installation constraints.',
    ],
    featuredModels: [
      'weichai-6m31d740e310',
      'weichai-6m31d680e310',
      'weichai-wp7d185e310',
      'weichai-wp10d264e200',
      'weichai-wp10d200e200',
      'weichai-wp13d405e200',
      'weichai-12m33d1320e310',
      'weichai-16m33d1580e310',
      'weichai-20m33d2210e310',
      'weichai-wp2-3d40e200',
    ],
    commonSearches: [
      'weichai generator',
      'weichai generator engine',
      'weichai engine specs',
      'weichai engine models',
      'weichai diesel generator',
      'weichai vs cummins',
    ],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: 'China Stage III engines', href: '/engines/emissions/china-stage-iii' },
      { label: '500-1,500 kWe engines', href: '/engines/power/500-1500-kwe' },
      { label: 'Generator engine selection guide', href: '/guides/how-to-choose-a-generator-engine' },
      { label: 'Generator sizing guide', href: '/guides/how-to-size-a-generator' },
    ],
    cta: {
      title: 'Need a Weichai generator package review?',
      body: 'Haifeng Machinery can help compare Weichai WP and M-series engine ratings with alternator, controller, enclosure, voltage, emissions documentation and export-market package requirements.',
      primaryLabel: 'Request Weichai package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Product offerings',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
  'waukesha': {
    title: 'Waukesha Gas Generator Engine Specs',
    h1: 'Waukesha Gas Generator Engines',
    description: 'Browse Waukesha gas generator engine specs for industrial gas power projects, including model ratings, fuel context, datasheets and package review notes.',
    overview: 'Waukesha generator engines in this database are relevant for gas generator buyers comparing industrial gas-engine power, long-runtime operation and project-level package requirements. Use this hub to compare model ratings, fuel context, datasheet coverage and related gas-generator resources before selecting the complete system.',
    applications: [
      'Industrial gas generator systems',
      'Long-runtime prime-power projects where gas supply is stable',
      'Oil and gas, utility, remote site and industrial facility power',
      'Custom EPC gas generator projects with switchgear, cooling and controls coordination',
    ],
    howToChoose: [
      'Start with gas supply, fuel quality and expected annual operating hours.',
      'Compare Waukesha model ratings against the required prime or continuous-duty load.',
      'Confirm gas train, emissions, cooling, alternator voltage, switchgear and controls before final package selection.',
    ],
    featuredModels: ['waukesha-vhp-l7044gsi', 'waukesha-vhp-l7042gsi', 'waukesha-vhp-f3524gsi', 'waukesha-275gl-16v'],
    commonSearches: ['waukesha generators', 'waukesha generator', 'waukesha gas engine', 'waukesha gas generator'],
    links: [
      { label: 'CNG and LPG gas generator systems', href: GAS_PACKAGE_URL },
      { label: 'Custom EPC power solutions', href: CUSTOM_EPC_URL },
      { label: 'Gas generator engines', href: '/engines/fuel/gas' },
      { label: 'Gas vs diesel TCO guide', href: '/guides/diesel-vs-natural-gas-total-cost-of-ownership' },
      { label: 'Generator paralleling guide', href: '/guides/generator-paralleling-explained' },
    ],
    cta: {
      title: 'Need a Waukesha gas generator package review?',
      body: 'Haifeng Machinery can help compare Waukesha gas engine options with alternator, gas train, cooling, controller, switchgear and documentation requirements for complete gas generator projects.',
      primaryLabel: 'Request Waukesha package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Gas generator packages',
      secondaryHref: GAS_PACKAGE_URL,
    },
  },
  'yunnei': {
    title: 'Yunnei Generator Engine Specs',
    h1: 'Yunnei Generator Engines',
    description: 'Browse Yunnei generator engine specs for compact and mid-range diesel gensets, including DEF20, DEF30, DEF47 and D6 model ratings, emissions and datasheets.',
    overview: 'Yunnei generator engines in this database are useful for buyers comparing compact and mid-range diesel genset options from Kunming Yunnei. The hub includes DEF20, DEF30, DEF47 and D6-series models with Euro Stage V, China Stage III and unregulated-market context, plus datasheet coverage for power-generation package review.',
    applications: [
      'Compact commercial and telecom diesel generator sets',
      'Small industrial standby and prime-power packages',
      'Export-market diesel generator packages using China Stage III or unregulated configurations',
      'Regulated compact generator projects where Euro Stage V documentation is required',
      'Agricultural, municipal, workshop and facility backup power where serviceability and package size matter',
    ],
    howToChoose: [
      'Start by separating DEF20, DEF30, DEF47 and D6 model families, because the suitable kWe band changes quickly across the range.',
      'Confirm whether the project needs Euro Stage V, China Stage III or unregulated-market documentation before quoting a generator set.',
      'Compare the engine rating with the actual standby or prime load, then check alternator frame, controller, enclosure cooling and voltage.',
      'Use the Yunnei catalog or model datasheet to confirm dimensions, fuel consumption and installation constraints before final package selection.',
    ],
    featuredModels: [
      'yunnei-def47czka5',
      'yunnei-def20nka4',
      'yunnei-def20cra4',
      'yunnei-def20csa4',
      'yunnei-def30cca5',
      'yunnei-def30cea5',
      'yunnei-def30taa3',
      'yunnei-d6r225-35cr',
    ],
    commonSearches: [
      'yunnei generator',
      'yunnei engine',
      'yunnei diesel generator',
      'yunnei generator engine',
      'yunnei def20',
      'yunnei def47',
    ],
    links: [
      { label: 'Haifeng product offerings', href: DIESEL_NON_REGULATED_URL },
      { label: 'Under 100 kWe engines', href: '/engines/power/under-100-kwe' },
      { label: '100-500 kWe engines', href: '/engines/power/100-500-kwe' },
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: 'Euro Stage V engines', href: '/engines/emissions/euro-stage-v' },
      { label: 'China Stage III engines', href: '/engines/emissions/china-stage-iii' },
      { label: 'Generator sizing guide', href: '/guides/how-to-size-a-generator' },
    ],
    cta: {
      title: 'Need a Yunnei diesel generator package review?',
      body: 'Haifeng Machinery can help compare Yunnei DEF and D-series engine ratings with alternator, controller, enclosure, voltage, emissions documentation and export-market package requirements.',
      primaryLabel: 'Request Yunnei package support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Product offerings',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
  'detroit-diesel': {
    title: 'Detroit Diesel Generator Engine Specs',
    h1: 'Detroit Diesel Generator Engines',
    description: 'Browse Detroit Diesel generator engine specs for gensets, including 16V149, 12V149, Series 60, 8V-92TA and legacy diesel power ratings with datasheets.',
    overview: 'Detroit Diesel generator engines in this database are useful for legacy genset lookup, replacement research and diesel package comparison. The hub includes V-series and Series 60 models with kWe output, displacement, emissions context and datasheet links where available.',
    applications: [
      'Legacy industrial generator-set replacement and reference work',
      'Marine, standby and prime diesel power packages',
      'Service, overhaul and sourcing research for older Detroit Diesel gensets',
    ],
    howToChoose: [
      'Start with the exact Detroit Diesel model family because legacy model names are easy to confuse.',
      'Compare kWe output and displacement against the existing alternator and generator frame.',
      'Check emissions and market restrictions carefully before quoting a legacy diesel engine.',
    ],
    featuredModels: ['detroit-diesel-16v149', 'detroit-diesel-12v149', 'detroit-diesel-series-60-14-0l', 'detroit-diesel-8v-92ta', 'detroit-diesel-series-60-12-7l'],
    commonSearches: ['genset detroit', 'detroit diesel generator sets', 'detroit diesel generator engine', 'detroit diesel genset'],
    links: [
      { label: 'Diesel generator engines', href: '/engines/fuel/diesel' },
      { label: '500-1,500 kWe engines', href: '/engines/power/500-1500-kwe' },
      { label: 'Generator engine selection guide', href: '/guides/how-to-choose-a-generator-engine' },
    ],
    cta: {
      title: 'Need help replacing or matching a Detroit Diesel genset?',
      body: 'Haifeng Machinery can help compare legacy Detroit Diesel ratings with available generator package options, alternator requirements and replacement-path constraints.',
      primaryLabel: 'Request Detroit Diesel support',
      primaryHref: CONTACT_URL,
      secondaryLabel: 'Diesel generator packages',
      secondaryHref: DIESEL_NON_REGULATED_URL,
    },
  },
}

export function brandHubProfile(slug: string): BrandHubProfile | null {
  return BRAND_HUB_PROFILES[slug] ?? null
}
